name = 'Typo'
license = 'MIT'
licenselink = 'https://github.com/tomfran/typo/LICENSE'
description = 'A simple Hugo theme'

homepage = 'https://github.com/tomfran/typo'

demosite = 'https://tomfran.github.io/'

tags = ['blog', 'minimal']

[author]
name = 'Francesco Tomaselli'
homepage = 'https://tomfran.github.io/'
